# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/ord_kit/proto/ord_kit_reaction.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app/ord_kit/proto/ord_kit_reaction.proto", :syntax => :proto3) do
    add_message "ord_kit.Reaction" do
      repeated :identifiers, :message, 1, "ord_kit.ReactionIdentifier"
      map :inputs, :string, :message, 2, "ord_kit.ReactionInput"
      optional :setup, :message, 3, "ord_kit.ReactionSetup"
      optional :conditions, :message, 4, "ord_kit.ReactionConditions"
      optional :notes, :message, 5, "ord_kit.ReactionNotes"
      repeated :observations, :message, 6, "ord_kit.ReactionObservation"
      repeated :workups, :message, 7, "ord_kit.ReactionWorkup"
      repeated :outcomes, :message, 8, "ord_kit.ReactionOutcome"
      optional :provenance, :message, 9, "ord_kit.ReactionProvenance"
      optional :reaction_id, :string, 10
      repeated :reaction_steps, :message, 11, "ord_kit.ReactionStep"
    end
    add_message "ord_kit.ReactionStep" do
      optional :reaction_step_id, :string, 1
      optional :position, :int32, 2
      optional :setup, :message, 3, "ord_kit.ReactionSetup"
      repeated :actions, :message, 4, "ord_kit.ReactionAction"
      optional :start_time, :message, 5, "ord_kit.Time"
      optional :duration, :message, 6, "ord_kit.Time"
      repeated :outcomes, :message, 7, "ord_kit.ReactionOutcome"
    end
    add_message "ord_kit.ReactionIdentifier" do
      optional :type, :enum, 1, "ord_kit.ReactionIdentifier.IdentifierType"
      optional :details, :string, 2
      optional :value, :string, 3
      proto3_optional :is_mapped, :bool, 4
    end
    add_enum "ord_kit.ReactionIdentifier.IdentifierType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :REACTION_SMILES, 2
      value :REACTION_CXSMILES, 6
      value :RDFILE, 3
      value :RINCHI, 4
      value :NAME, 5
    end
    add_message "ord_kit.ReactionInput" do
      repeated :components, :message, 1, "ord_kit.Compound"
      repeated :crude_components, :message, 2, "ord_kit.CrudeComponent"
      optional :addition_order, :int32, 3
      optional :addition_time, :message, 4, "ord_kit.Time"
      optional :addition_speed, :message, 5, "ord_kit.ReactionInput.AdditionSpeed"
      optional :addition_duration, :message, 6, "ord_kit.Time"
      optional :flow_rate, :message, 7, "ord_kit.FlowRate"
      optional :addition_device, :message, 8, "ord_kit.Equipment"
      optional :addition_temperature, :message, 9, "ord_kit.Temperature"
      optional :addition_pressure, :message, 10, "ord_kit.Pressure"
    end
    add_message "ord_kit.ReactionInput.AdditionSpeed" do
      optional :type, :enum, 1, "ord_kit.ReactionInput.AdditionSpeed.AdditionSpeedType"
      optional :details, :string, 2
    end
    add_enum "ord_kit.ReactionInput.AdditionSpeed.AdditionSpeedType" do
      value :UNSPECIFIED, 0
      value :ALL_AT_ONCE, 1
      value :FAST, 2
      value :SLOW, 3
      value :DROPWISE, 4
      value :CONTINUOUS, 5
      value :PORTIONWISE, 6
      value :FLOW_RATE, 7
    end
    add_message "ord_kit.ReactionAction" do
      optional :description, :string, 1
      optional :position, :int32, 2
      optional :start_time, :message, 3, "ord_kit.Time"
      optional :duration, :message, 4, "ord_kit.Time"
      optional :extra_equipment, :message, 5, "ord_kit.Equipment"
      oneof :action do
        optional :addition, :message, 6, "ord_kit.ReactionActionAdd"
        optional :removal, :message, 7, "ord_kit.ReactionActionRemove"
        optional :equip, :message, 8, "ord_kit.ReactionActionEquip"
        optional :condition, :message, 9, "ord_kit.ReactionActionCondition"
        optional :motion, :message, 10, "ord_kit.ReactionActionMotion"
        optional :purify, :message, 11, "ord_kit.ReactionActionPurify"
        optional :transfer, :message, 12, "ord_kit.ReactionActionTransfer"
        optional :wait, :message, 13, "ord_kit.ReactionActionWait"
        optional :save_sample, :message, 14, "ord_kit.ReactionActionSaveSample"
        optional :analysis, :message, 15, "ord_kit.Analysis"
      end
    end
    add_message "ord_kit.ReactionActionAdd" do
      optional :reaction_role, :enum, 1, "ord_kit.ReactionRole.ReactionRoleType"
      optional :input, :message, 2, "ord_kit.ReactionInput"
    end
    add_message "ord_kit.ReactionActionRemove" do
      proto3_optional :reaction_role, :enum, 1, "ord_kit.ReactionRole.ReactionRoleType"
      optional :input, :message, 2, "ord_kit.ReactionInput"
      optional :reaction_replacement_medium, :message, 3, "ord_kit.Compound"
      optional :removal_repetitions, :int32, 4
    end
    add_message "ord_kit.ReactionActionEquip" do
      optional :mount_action, :enum, 1, "ord_kit.ReactionActionEquip.EquipActionType"
      optional :equipment, :message, 2, "ord_kit.Equipment"
    end
    add_enum "ord_kit.ReactionActionEquip.EquipActionType" do
      value :UNSPECIFIED, 0
      value :MOUNT, 1
      value :UNMOUNT, 2
    end
    add_message "ord_kit.ReactionActionCondition" do
      optional :conditions, :message, 1, "ord_kit.ReactionConditions"
      optional :tendency, :enum, 2, "ord_kit.ReactionActionCondition.TendencyType"
      optional :details, :string, 3
    end
    add_enum "ord_kit.ReactionActionCondition.TendencyType" do
      value :UNSPECIFIED, 0
      value :INCREASE, 1
      value :DECREASE, 2
    end
    add_message "ord_kit.ReactionActionMotion" do
      optional :motion, :message, 1, "ord_kit.StirringConditions"
    end
    add_message "ord_kit.ReactionActionPurify" do
      optional :type, :enum, 1, "ord_kit.ReactionActionPurify.PurifyType"
      optional :automation, :enum, 2, "ord_kit.Automation.AutomationType"
      repeated :solvents, :message, 3, "ord_kit.Compound"
      optional :ratio, :string, 4
      proto3_optional :filtration_mode, :enum, 5, "ord_kit.ReactionActionPurify.FiltrationMode"
    end
    add_enum "ord_kit.ReactionActionPurify.PurifyType" do
      value :UNSPECIFIED, 0
      value :CHROMATOGRAPHY, 1
      value :EXTRACTION, 2
      value :FILTRATION, 3
      value :CRYSTALLIZATION, 4
    end
    add_enum "ord_kit.ReactionActionPurify.FiltrationMode" do
      value :KEEP_UNSPECIFIED, 0
      value :KEEP_PERMEATE, 1
      value :KEEP_RETENTATE, 2
    end
    add_message "ord_kit.ReactionActionTransfer" do
      optional :sample, :message, 1, "ord_kit.Compound"
      optional :transfer_source_reaction_step_id, :string, 2
      optional :transfer_target_reaction_step_id, :string, 3
      optional :amount, :message, 4, "ord_kit.Amount"
    end
    add_message "ord_kit.ReactionActionWait" do
      optional :duration, :message, 1, "ord_kit.Time"
    end
    add_message "ord_kit.ReactionActionSaveSample" do
      optional :sample, :message, 1, "ord_kit.Compound"
    end
    add_message "ord_kit.Amount" do
      proto3_optional :volume_includes_solutes, :bool, 4
      oneof :kind do
        optional :mass, :message, 1, "ord_kit.Mass"
        optional :moles, :message, 2, "ord_kit.Moles"
        optional :volume, :message, 3, "ord_kit.Volume"
        optional :unmeasured, :message, 5, "ord_kit.UnmeasuredAmount"
        optional :percentage, :message, 6, "ord_kit.Percentage"
      end
    end
    add_message "ord_kit.UnmeasuredAmount" do
      optional :type, :enum, 1, "ord_kit.UnmeasuredAmount.UnmeasuredAmountType"
      optional :details, :string, 2
    end
    add_enum "ord_kit.UnmeasuredAmount.UnmeasuredAmountType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :SATURATED, 2
      value :CATALYTIC, 3
      value :TITRATED, 4
    end
    add_message "ord_kit.CrudeComponent" do
      optional :reaction_id, :string, 1
      proto3_optional :includes_workup, :bool, 2
      proto3_optional :has_derived_amount, :bool, 3
      optional :amount, :message, 4, "ord_kit.Amount"
    end
    add_message "ord_kit.Compound" do
      repeated :identifiers, :message, 1, "ord_kit.CompoundIdentifier"
      optional :amount, :message, 2, "ord_kit.Amount"
      optional :reaction_role, :enum, 3, "ord_kit.ReactionRole.ReactionRoleType"
      proto3_optional :is_limiting, :bool, 4
      repeated :preparations, :message, 5, "ord_kit.CompoundPreparation"
      optional :source, :message, 6, "ord_kit.Compound.Source"
      map :features, :string, :message, 7, "ord_kit.Data"
      map :analyses, :string, :message, 8, "ord_kit.Analysis"
      optional :purity, :message, 9, "ord_kit.Percentage"
      proto3_optional :is_waterfree_solvent, :bool, 10
    end
    add_message "ord_kit.Compound.Source" do
      optional :vendor, :string, 1
      optional :id, :string, 2
      optional :lot, :string, 3
    end
    add_message "ord_kit.ReactionRole" do
    end
    add_enum "ord_kit.ReactionRole.ReactionRoleType" do
      value :UNSPECIFIED, 0
      value :REACTANT, 1
      value :REAGENT, 2
      value :SOLVENT, 3
      value :CATALYST, 4
      value :WORKUP, 5
      value :INTERNAL_STANDARD, 6
      value :AUTHENTIC_STANDARD, 7
      value :PRODUCT, 8
      value :SAMPLE, 9
      value :DIVERSE_SOLVENT, 10
      value :ADDITIVE, 11
      value :MEDIUM, 12
      value :CRUDE, 13
      value :INTERMEDIATE, 14
      value :MIXTURE, 15
    end
    add_message "ord_kit.CompoundPreparation" do
      repeated :type, :enum, 1, "ord_kit.CompoundPreparation.PreparationType"
      optional :details, :string, 2
      optional :reaction_id, :string, 3
      repeated :equipment, :message, 4, "ord_kit.Equipment"
    end
    add_enum "ord_kit.CompoundPreparation.PreparationType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :NONE, 2
      value :REPURIFIED, 3
      value :SPARGED, 4
      value :DRIED, 5
      value :SYNTHESIZED, 6
      value :DISSOLVED, 7
      value :HOMOGENIZED, 8
      value :TEMPERATURE_ADJUSTED, 9
      value :DEGASSED, 10
    end
    add_message "ord_kit.CompoundIdentifier" do
      optional :type, :enum, 1, "ord_kit.CompoundIdentifier.IdentifierType"
      optional :details, :string, 2
      optional :value, :string, 3
    end
    add_enum "ord_kit.CompoundIdentifier.IdentifierType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :SMILES, 2
      value :INCHI, 3
      value :MOLBLOCK, 4
      value :IUPAC_NAME, 5
      value :NAME, 6
      value :CAS_NUMBER, 7
      value :PUBCHEM_CID, 8
      value :CHEMSPIDER_ID, 9
      value :CXSMILES, 10
      value :INCHI_KEY, 11
      value :XYZ, 12
      value :UNIPROT_ID, 13
      value :PDB_ID, 14
      value :AMINO_ACID_SEQUENCE, 15
      value :HELM, 16
    end
    add_message "ord_kit.Vessel" do
      optional :type, :enum, 1, "ord_kit.Vessel.VesselType"
      optional :details, :string, 2
      optional :material, :message, 3, "ord_kit.VesselMaterial"
      repeated :preparations, :message, 4, "ord_kit.VesselPreparation"
      repeated :attachments, :message, 5, "ord_kit.VesselAttachment"
      optional :volume, :message, 6, "ord_kit.Volume"
      optional :plate_id, :string, 7
      optional :plate_position, :string, 8
    end
    add_enum "ord_kit.Vessel.VesselType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :ROUND_BOTTOM_FLASK, 2
      value :VIAL, 3
      value :WELL_PLATE, 4
      value :MICROWAVE_VIAL, 5
      value :TUBE, 6
      value :CONTINUOUS_STIRRED_TANK_REACTOR, 7
      value :PACKED_BED_REACTOR, 8
      value :NMR_TUBE, 9
      value :PRESSURE_FLASK, 10
      value :PRESSURE_REACTOR, 11
      value :ELECTROCHEMICAL_CELL, 12
      value :SCHLENK_FLASK, 13
      value :SCHLENK_TUBE, 14
      value :MULTINECK_FLASK, 15
      value :COIL, 16
      value :CUVETTE, 17
      value :BEAKER, 18
      value :ERLENMEYER_FLASK, 19
    end
    add_message "ord_kit.VesselMaterial" do
      optional :type, :enum, 1, "ord_kit.VesselMaterial.VesselMaterialType"
      optional :details, :string, 2
    end
    add_enum "ord_kit.VesselMaterial.VesselMaterialType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :GLASS, 2
      value :POLYPROPYLENE, 3
      value :PLASTIC, 4
      value :METAL, 5
      value :QUARTZ, 6
      value :BROWN_GLASS, 7
      value :PFA, 8
      value :PTFE, 9
    end
    add_message "ord_kit.Equipment" do
      optional :type, :enum, 1, "ord_kit.Equipment.EquipmentType"
      optional :details, :string, 2
    end
    add_enum "ord_kit.Equipment.EquipmentType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :NONE, 2
      value :SYRINGE, 3
      value :CANNULA, 4
      value :ADDITION_FUNNEL, 5
      value :SPATULA, 6
      value :PIPE, 7
      value :PIPET, 8
      value :FLASK, 9
      value :DOSING_STATION, 10
      value :LIQUID_HANDLING_SYSTEM, 11
      value :SYRING_AND_SYRINGE_PUMP, 12
      value :HEATING_MANTLE, 13
      value :BLOW_DRYER, 14
      value :OIL_BATH, 15
      value :ICE_BATH, 16
      value :ALUMINIUM_BLOCK, 17
      value :WATER_BATH, 18
      value :SAND_BATH, 19
      value :REACTOR, 20
      value :ULTRA_SOUND_BATH, 21
      value :UV_LAMP, 22
      value :LED, 23
      value :STIRRER, 24
      value :SHAKER, 25
      value :HEATING_SHAKER, 26
      value :TUBE, 27
      value :BALL_MILLING, 28
      value :PUMP, 29
      value :COIL, 30
      value :FILTER, 31
      value :SEPARATION_FUNNEL, 32
      value :EXTRACTOR, 33
      value :SPE_COLUMN, 34
      value :FSPE_COLUMN, 35
      value :FLASH_COLUMN, 36
      value :DISTILLATION_APPARATUS, 37
      value :DROPPING_FUNNEL, 38
      value :BUCHNER_FUNNEL, 39
      value :MICROWAVE_REACTOR, 40
      value :CHROMATOGRAPHY_DEVICE, 41
      value :HPLC, 42
      value :HPLC_COLUMN, 43
      value :CARTRIDGE, 44
    end
    add_message "ord_kit.VesselAttachment" do
      optional :type, :enum, 1, "ord_kit.VesselAttachment.VesselAttachmentType"
      optional :details, :string, 2
    end
    add_enum "ord_kit.VesselAttachment.VesselAttachmentType" do
      value :UNSPECIFIED, 0
      value :NONE, 1
      value :CUSTOM, 2
      value :SEPTUM, 3
      value :CAP, 4
      value :MAT, 5
      value :REFLUX_CONDENSER, 6
      value :VENT_NEEDLE, 7
      value :DEAN_STARK, 8
      value :VACUUM_TUBE, 9
      value :ADDITION_FUNNEL, 10
      value :DRYING_TUBE, 11
      value :ALUMINUM_FOIL, 12
      value :THERMOCOUPLE, 13
      value :BALLOON, 14
      value :GAS_ADAPTER, 15
      value :PRESSURE_REGULATOR, 16
      value :RELEASE_VALVE, 17
      value :STIRRING_BAR, 18
      value :CANNULA, 19
      value :FINDENSER, 20
      value :PRESSURE_CAPS_VIALS, 21
      value :TUBE, 22
      value :STOPPER, 23
      value :METAL_REFLUX_CONDENSER, 24
      value :SOXHLET_EXTRACTOR, 25
      value :OVERHEAD_STIRRER, 26
      value :FUNNEL, 27
      value :DROPPING_FUNNEL, 28
      value :SEPARATION_FUNNEL, 29
      value :HYDRATION_APPARATUS, 30
    end
    add_message "ord_kit.VesselPreparation" do
      optional :type, :enum, 1, "ord_kit.VesselPreparation.VesselPreparationType"
      optional :details, :string, 2
      optional :medium, :string, 3
    end
    add_enum "ord_kit.VesselPreparation.VesselPreparationType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :NONE, 2
      value :OVEN_DRIED, 3
      value :FLAME_DRIED, 4
      value :EVACUATED_BACKFILLED, 5
      value :PURGED, 6
    end
    add_message "ord_kit.ReactionSetup" do
      optional :vessel, :message, 1, "ord_kit.Vessel"
      proto3_optional :is_automated, :bool, 2
      optional :automation_platform, :string, 3
      map :automation_code, :string, :message, 4, "ord_kit.Data"
      optional :environment, :message, 5, "ord_kit.ReactionSetup.ReactionEnvironment"
    end
    add_message "ord_kit.ReactionSetup.ReactionEnvironment" do
      optional :type, :enum, 1, "ord_kit.ReactionSetup.ReactionEnvironment.ReactionEnvironmentType"
      optional :details, :string, 2
    end
    add_enum "ord_kit.ReactionSetup.ReactionEnvironment.ReactionEnvironmentType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :FUME_HOOD, 2
      value :BENCH_TOP, 3
      value :GLOVE_BOX, 4
      value :GLOVE_BAG, 5
    end
    add_message "ord_kit.ReactionConditions" do
      optional :temperature, :message, 1, "ord_kit.TemperatureConditions"
      optional :pressure, :message, 2, "ord_kit.PressureConditions"
      optional :stirring, :message, 3, "ord_kit.StirringConditions"
      optional :illumination, :message, 4, "ord_kit.IlluminationConditions"
      optional :electrochemistry, :message, 5, "ord_kit.ElectrochemistryConditions"
      optional :flow, :message, 6, "ord_kit.FlowConditions"
      proto3_optional :reflux, :bool, 7
      optional :ph, :message, 8, "ord_kit.PhAdjustConditions"
      proto3_optional :conditions_are_dynamic, :bool, 9
      optional :details, :string, 10
    end
    add_message "ord_kit.PhAdjustConditions" do
      optional :measurement_type, :enum, 1, "ord_kit.PhAdjustConditions.PhAdjustMeasurementType"
      optional :ph, :double, 2
    end
    add_enum "ord_kit.PhAdjustConditions.PhAdjustMeasurementType" do
      value :UNSPECIFIED, 0
      value :ELECTRODE, 1
      value :STRIPE, 2
      value :OTHER, 3
    end
    add_message "ord_kit.TemperatureConditions" do
      optional :control, :message, 1, "ord_kit.TemperatureConditions.TemperatureControl"
      optional :setpoint, :message, 2, "ord_kit.Temperature"
      repeated :measurements, :message, 3, "ord_kit.TemperatureConditions.Measurement"
    end
    add_message "ord_kit.TemperatureConditions.TemperatureControl" do
      optional :type, :enum, 1, "ord_kit.TemperatureConditions.TemperatureControl.TemperatureControlType"
      optional :details, :string, 2
    end
    add_enum "ord_kit.TemperatureConditions.TemperatureControl.TemperatureControlType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :AMBIENT, 2
      value :OIL_BATH, 3
      value :WATER_BATH, 4
      value :SAND_BATH, 5
      value :ICE_BATH, 6
      value :DRY_ALUMINUM_PLATE, 7
      value :MICROWAVE, 8
      value :DRY_ICE_BATH, 9
      value :AIR_FAN, 10
      value :LIQUID_NITROGEN, 11
      value :MEASUREMENT_IN_REACTION, 12
      value :CONTACT_MEDIUM, 13
    end
    add_message "ord_kit.TemperatureConditions.Measurement" do
      optional :type, :enum, 1, "ord_kit.TemperatureConditions.Measurement.MeasurementType"
      optional :details, :string, 2
      optional :time, :message, 3, "ord_kit.Time"
      optional :temperature, :message, 4, "ord_kit.Temperature"
    end
    add_enum "ord_kit.TemperatureConditions.Measurement.MeasurementType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :THERMOCOUPLE_INTERNAL, 2
      value :THERMOCOUPLE_EXTERNAL, 3
      value :INFRARED, 4
    end
    add_message "ord_kit.PressureConditions" do
      optional :control, :message, 1, "ord_kit.PressureConditions.PressureControl"
      optional :setpoint, :message, 2, "ord_kit.Pressure"
      optional :atmosphere, :message, 3, "ord_kit.PressureConditions.Atmosphere"
      repeated :measurements, :message, 4, "ord_kit.PressureConditions.Measurement"
    end
    add_message "ord_kit.PressureConditions.PressureControl" do
      optional :type, :enum, 1, "ord_kit.PressureConditions.PressureControl.PressureControlType"
      optional :details, :string, 2
    end
    add_enum "ord_kit.PressureConditions.PressureControl.PressureControlType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :AMBIENT, 2
      value :SLIGHT_POSITIVE, 3
      value :SEALED, 4
      value :PRESSURIZED, 5
    end
    add_message "ord_kit.PressureConditions.Atmosphere" do
      optional :type, :enum, 1, "ord_kit.PressureConditions.Atmosphere.AtmosphereType"
      optional :details, :string, 2
    end
    add_enum "ord_kit.PressureConditions.Atmosphere.AtmosphereType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :AIR, 2
      value :NITROGEN, 3
      value :ARGON, 4
      value :OXYGEN, 5
      value :HYDROGEN, 6
      value :CARBON_MONOXIDE, 7
      value :CARBON_DIOXIDE, 8
      value :METHANE, 9
      value :AMMONIA, 10
      value :OZONE, 11
      value :ETHYLENE, 12
      value :ACETYLENE, 13
    end
    add_message "ord_kit.PressureConditions.Measurement" do
      optional :type, :enum, 1, "ord_kit.PressureConditions.Measurement.MeasurementType"
      optional :details, :string, 2
      optional :time, :message, 3, "ord_kit.Time"
      optional :pressure, :message, 4, "ord_kit.Pressure"
    end
    add_enum "ord_kit.PressureConditions.Measurement.MeasurementType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :PRESSURE_TRANSDUCER, 2
    end
    add_message "ord_kit.StirringConditions" do
      optional :type, :enum, 1, "ord_kit.StirringConditions.StirringMethodType"
      optional :details, :string, 2
      optional :rate, :message, 3, "ord_kit.StirringConditions.StirringRate"
      optional :automation, :enum, 4, "ord_kit.Automation.AutomationType"
    end
    add_message "ord_kit.StirringConditions.StirringRate" do
      optional :type, :enum, 1, "ord_kit.StirringConditions.StirringRate.StirringRateType"
      optional :details, :string, 2
      optional :rpm, :int32, 3
    end
    add_enum "ord_kit.StirringConditions.StirringRate.StirringRateType" do
      value :UNSPECIFIED, 0
      value :HIGH, 1
      value :MEDIUM, 2
      value :LOW, 3
    end
    add_enum "ord_kit.StirringConditions.StirringMethodType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :NONE, 2
      value :STIR_BAR, 3
      value :OVERHEAD_MIXER, 4
      value :AGITATION, 5
      value :BALL_MILLING, 6
      value :SONICATION, 7
      value :OTHER, 8
    end
    add_message "ord_kit.IlluminationConditions" do
      optional :type, :enum, 1, "ord_kit.IlluminationConditions.IlluminationType"
      optional :details, :string, 2
      optional :peak_wavelength, :message, 3, "ord_kit.Wavelength"
      optional :color, :string, 4
      optional :distance_to_vessel, :message, 5, "ord_kit.Length"
    end
    add_enum "ord_kit.IlluminationConditions.IlluminationType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :AMBIENT, 2
      value :DARK, 3
      value :LED, 4
      value :HALOGEN_LAMP, 5
      value :DEUTERIUM_LAMP, 6
      value :SOLAR_SIMULATOR, 7
      value :BROAD_SPECTRUM, 8
      value :LAMP, 9
      value :LASER, 10
    end
    add_message "ord_kit.ElectrochemistryConditions" do
      optional :type, :enum, 1, "ord_kit.ElectrochemistryConditions.ElectrochemistryType"
      optional :details, :string, 2
      optional :current, :message, 3, "ord_kit.Current"
      optional :voltage, :message, 4, "ord_kit.Voltage"
      optional :anode_material, :string, 5
      optional :cathode_material, :string, 6
      optional :electrode_separation, :message, 7, "ord_kit.Length"
      repeated :measurements, :message, 8, "ord_kit.ElectrochemistryConditions.Measurement"
      optional :cell, :message, 9, "ord_kit.ElectrochemistryConditions.ElectrochemistryCell"
    end
    add_message "ord_kit.ElectrochemistryConditions.Measurement" do
      optional :time, :message, 1, "ord_kit.Time"
      oneof :kind do
        optional :current, :message, 2, "ord_kit.Current"
        optional :voltage, :message, 3, "ord_kit.Voltage"
      end
    end
    add_message "ord_kit.ElectrochemistryConditions.ElectrochemistryCell" do
      optional :type, :enum, 1, "ord_kit.ElectrochemistryConditions.ElectrochemistryCell.ElectrochemistryCellType"
      optional :details, :string, 2
    end
    add_enum "ord_kit.ElectrochemistryConditions.ElectrochemistryCell.ElectrochemistryCellType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :DIVIDED_CELL, 2
      value :UNDIVIDED_CELL, 3
    end
    add_enum "ord_kit.ElectrochemistryConditions.ElectrochemistryType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :CONSTANT_CURRENT, 2
      value :CONSTANT_VOLTAGE, 3
    end
    add_message "ord_kit.FlowConditions" do
      optional :type, :enum, 1, "ord_kit.FlowConditions.FlowType"
      optional :details, :string, 2
      optional :pump_type, :string, 3
      optional :tubing, :message, 4, "ord_kit.FlowConditions.Tubing"
    end
    add_message "ord_kit.FlowConditions.Tubing" do
      optional :type, :enum, 1, "ord_kit.FlowConditions.Tubing.TubingType"
      optional :details, :string, 2
      optional :diameter, :message, 3, "ord_kit.Length"
    end
    add_enum "ord_kit.FlowConditions.Tubing.TubingType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :STEEL, 2
      value :COPPER, 3
      value :PFA, 4
      value :FEP, 5
      value :TEFLONAF, 6
      value :PTFE, 7
      value :GLASS, 8
      value :QUARTZ, 9
      value :SILICON, 10
      value :PDMS, 11
    end
    add_enum "ord_kit.FlowConditions.FlowType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :PLUG_FLOW_REACTOR, 2
      value :CONTINUOUS_STIRRED_TANK_REACTOR, 3
      value :PACKED_BED_REACTOR, 4
    end
    add_message "ord_kit.ReactionNotes" do
      proto3_optional :is_heterogeneous, :bool, 1
      proto3_optional :forms_precipitate, :bool, 2
      proto3_optional :is_exothermic, :bool, 3
      proto3_optional :offgasses, :bool, 4
      proto3_optional :is_sensitive_to_moisture, :bool, 5
      proto3_optional :is_sensitive_to_oxygen, :bool, 6
      proto3_optional :is_sensitive_to_light, :bool, 7
      optional :safety_notes, :string, 8
      optional :process_details, :string, 9
    end
    add_message "ord_kit.ReactionObservation" do
      optional :time, :message, 1, "ord_kit.Time"
      optional :comment, :string, 2
      optional :image, :message, 3, "ord_kit.Data"
    end
    add_message "ord_kit.ReactionWorkup" do
      optional :type, :enum, 1, "ord_kit.ReactionWorkup.WorkupType"
      optional :details, :string, 2
      optional :duration, :message, 3, "ord_kit.Time"
      optional :input, :message, 4, "ord_kit.ReactionInput"
      optional :amount, :message, 5, "ord_kit.Amount"
      optional :temperature, :message, 6, "ord_kit.TemperatureConditions"
      optional :keep_phase, :string, 7
      optional :stirring, :message, 8, "ord_kit.StirringConditions"
      proto3_optional :target_ph, :double, 9
      proto3_optional :is_automated, :bool, 10
    end
    add_enum "ord_kit.ReactionWorkup.WorkupType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :ADDITION, 2
      value :ALIQUOT, 3
      value :TEMPERATURE, 4
      value :CONCENTRATION, 5
      value :EXTRACTION, 6
      value :FILTRATION, 7
      value :WASH, 8
      value :DRY_IN_VACUUM, 9
      value :DRY_WITH_MATERIAL, 10
      value :FLASH_CHROMATOGRAPHY, 11
      value :OTHER_CHROMATOGRAPHY, 12
      value :SCAVENGING, 13
      value :WAIT, 14
      value :STIRRING, 15
      value :PH_ADJUST, 16
      value :DISSOLUTION, 17
      value :DISTILLATION, 18
    end
    add_message "ord_kit.ReactionOutcome" do
      optional :reaction_time, :message, 1, "ord_kit.Time"
      optional :conversion, :message, 2, "ord_kit.Percentage"
      repeated :products, :message, 3, "ord_kit.ProductCompound"
      map :analyses, :string, :message, 4, "ord_kit.Analysis"
    end
    add_message "ord_kit.ProductCompound" do
      repeated :identifiers, :message, 1, "ord_kit.CompoundIdentifier"
      proto3_optional :is_desired_product, :bool, 2
      repeated :measurements, :message, 3, "ord_kit.ProductMeasurement"
      optional :isolated_color, :string, 4
      optional :texture, :message, 5, "ord_kit.ProductCompound.Texture"
      map :features, :string, :message, 6, "ord_kit.Data"
      optional :reaction_role, :enum, 7, "ord_kit.ReactionRole.ReactionRoleType"
    end
    add_message "ord_kit.ProductCompound.Texture" do
      optional :type, :enum, 1, "ord_kit.ProductCompound.Texture.TextureType"
      optional :details, :string, 2
    end
    add_enum "ord_kit.ProductCompound.Texture.TextureType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :POWDER, 2
      value :CRYSTAL, 3
      value :OIL, 4
      value :AMORPHOUS_SOLID, 5
      value :FOAM, 6
      value :WAX, 7
      value :SEMI_SOLID, 8
      value :SOLID, 9
      value :LIQUID, 10
    end
    add_message "ord_kit.ProductMeasurement" do
      optional :analysis_key, :string, 1
      optional :type, :enum, 2, "ord_kit.ProductMeasurement.MeasurementType"
      optional :details, :string, 3
      proto3_optional :uses_internal_standard, :bool, 4
      proto3_optional :is_normalized, :bool, 5
      proto3_optional :uses_authentic_standard, :bool, 6
      optional :authentic_standard, :message, 7, "ord_kit.Compound"
      optional :retention_time, :message, 12, "ord_kit.Time"
      optional :mass_spec_details, :message, 13, "ord_kit.ProductMeasurement.MassSpecMeasurementDetails"
      optional :selectivity, :message, 14, "ord_kit.ProductMeasurement.Selectivity"
      optional :wavelength, :message, 15, "ord_kit.Wavelength"
      oneof :value do
        optional :percentage, :message, 8, "ord_kit.Percentage"
        optional :float_value, :message, 9, "ord_kit.FloatValue"
        optional :string_value, :string, 10
        optional :amount, :message, 11, "ord_kit.Amount"
      end
    end
    add_message "ord_kit.ProductMeasurement.MassSpecMeasurementDetails" do
      optional :type, :enum, 1, "ord_kit.ProductMeasurement.MassSpecMeasurementDetails.MassSpecMeasurementType"
      optional :details, :string, 2
      proto3_optional :tic_minimum_mz, :float, 3
      proto3_optional :tic_maximum_mz, :float, 4
      repeated :eic_masses, :float, 5
    end
    add_enum "ord_kit.ProductMeasurement.MassSpecMeasurementDetails.MassSpecMeasurementType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :TIC, 2
      value :TIC_POSITIVE, 3
      value :TIC_NEGATIVE, 4
      value :EIC, 5
    end
    add_message "ord_kit.ProductMeasurement.Selectivity" do
      optional :type, :enum, 1, "ord_kit.ProductMeasurement.Selectivity.SelectivityType"
      optional :details, :string, 2
    end
    add_enum "ord_kit.ProductMeasurement.Selectivity.SelectivityType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :EE, 2
      value :ER, 3
      value :DR, 4
      value :EZ, 5
      value :ZE, 6
    end
    add_enum "ord_kit.ProductMeasurement.MeasurementType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :IDENTITY, 2
      value :YIELD, 3
      value :SELECTIVITY, 4
      value :PURITY, 5
      value :AREA, 6
      value :COUNTS, 7
      value :INTENSITY, 8
      value :AMOUNT, 9
    end
    add_message "ord_kit.DateTime" do
      optional :value, :string, 1
    end
    add_message "ord_kit.Analysis" do
      optional :type, :enum, 1, "ord_kit.Analysis.AnalysisType"
      optional :details, :string, 2
      optional :chmo_id, :int32, 3
      proto3_optional :is_of_isolated_species, :bool, 4
      map :data, :string, :message, 5, "ord_kit.Data"
      optional :instrument_manufacturer, :string, 6
      optional :instrument_last_calibrated, :message, 7, "ord_kit.DateTime"
      proto3_optional :number, :int32, 8
    end
    add_enum "ord_kit.Analysis.AnalysisType" do
      value :UNSPECIFIED, 0
      value :CUSTOM, 1
      value :LC, 2
      value :GC, 3
      value :IR, 4
      value :NMR_1H, 5
      value :NMR_13C, 6
      value :NMR_OTHER, 7
      value :MP, 8
      value :UV, 9
      value :TLC, 10
      value :MS, 11
      value :HRMS, 12
      value :MSMS, 13
      value :WEIGHT, 14
      value :LCMS, 15
      value :GCMS, 16
      value :ELSD, 17
      value :CD, 18
      value :SFC, 19
      value :EPR, 20
      value :XRD, 21
      value :RAMAN, 22
      value :ED, 23
    end
    add_message "ord_kit.ReactionProvenance" do
      optional :experimenter, :message, 1, "ord_kit.Person"
      optional :city, :string, 2
      optional :experiment_start, :message, 3, "ord_kit.DateTime"
      optional :doi, :string, 4
      optional :patent, :string, 5
      optional :publication_url, :string, 6
      optional :record_created, :message, 7, "ord_kit.RecordEvent"
      repeated :record_modified, :message, 8, "ord_kit.RecordEvent"
    end
    add_message "ord_kit.Person" do
      optional :username, :string, 1
      optional :name, :string, 2
      optional :orcid, :string, 3
      optional :organization, :string, 4
      optional :email, :string, 5
    end
    add_message "ord_kit.RecordEvent" do
      optional :time, :message, 1, "ord_kit.DateTime"
      optional :person, :message, 2, "ord_kit.Person"
      optional :details, :string, 3
    end
    add_message "ord_kit.Time" do
      proto3_optional :value, :float, 1
      proto3_optional :precision, :float, 2
      optional :units, :enum, 3, "ord_kit.Time.TimeUnit"
    end
    add_enum "ord_kit.Time.TimeUnit" do
      value :UNSPECIFIED, 0
      value :DAY, 4
      value :HOUR, 1
      value :MINUTE, 2
      value :SECOND, 3
    end
    add_message "ord_kit.Mass" do
      proto3_optional :value, :double, 1
      proto3_optional :precision, :double, 2
      optional :units, :enum, 3, "ord_kit.Mass.MassUnit"
    end
    add_enum "ord_kit.Mass.MassUnit" do
      value :UNSPECIFIED, 0
      value :KILOGRAM, 1
      value :GRAM, 2
      value :MILLIGRAM, 3
      value :MICROGRAM, 4
    end
    add_message "ord_kit.Moles" do
      proto3_optional :value, :double, 1
      proto3_optional :precision, :double, 2
      optional :units, :enum, 3, "ord_kit.Moles.MolesUnit"
    end
    add_enum "ord_kit.Moles.MolesUnit" do
      value :UNSPECIFIED, 0
      value :MOLE, 1
      value :MILLIMOLE, 2
      value :MICROMOLE, 3
      value :NANOMOLE, 4
    end
    add_message "ord_kit.Volume" do
      proto3_optional :value, :double, 1
      proto3_optional :precision, :double, 2
      optional :units, :enum, 3, "ord_kit.Volume.VolumeUnit"
    end
    add_enum "ord_kit.Volume.VolumeUnit" do
      value :UNSPECIFIED, 0
      value :LITER, 1
      value :MILLILITER, 2
      value :MICROLITER, 3
      value :NANOLITER, 4
    end
    add_message "ord_kit.Concentration" do
      proto3_optional :value, :double, 1
      proto3_optional :precision, :double, 2
      optional :units, :enum, 3, "ord_kit.Concentration.ConcentrationUnit"
    end
    add_enum "ord_kit.Concentration.ConcentrationUnit" do
      value :UNSPECIFIED, 0
      value :MOLAR, 1
      value :MILLIMOLAR, 2
      value :MICROMOLAR, 3
    end
    add_message "ord_kit.Pressure" do
      proto3_optional :value, :double, 1
      proto3_optional :precision, :double, 2
      optional :units, :enum, 3, "ord_kit.Pressure.PressureUnit"
    end
    add_enum "ord_kit.Pressure.PressureUnit" do
      value :UNSPECIFIED, 0
      value :BAR, 1
      value :ATMOSPHERE, 2
      value :PSI, 3
      value :KPSI, 4
      value :PASCAL, 5
      value :KILOPASCAL, 6
      value :TORR, 7
      value :MM_HG, 8
    end
    add_message "ord_kit.Temperature" do
      proto3_optional :value, :double, 1
      proto3_optional :precision, :double, 2
      optional :units, :enum, 3, "ord_kit.Temperature.TemperatureUnit"
    end
    add_enum "ord_kit.Temperature.TemperatureUnit" do
      value :UNSPECIFIED, 0
      value :CELSIUS, 1
      value :FAHRENHEIT, 2
      value :KELVIN, 3
    end
    add_message "ord_kit.Current" do
      proto3_optional :value, :double, 1
      proto3_optional :precision, :double, 2
      optional :units, :enum, 3, "ord_kit.Current.CurrentUnit"
    end
    add_enum "ord_kit.Current.CurrentUnit" do
      value :UNSPECIFIED, 0
      value :AMPERE, 1
      value :MILLIAMPERE, 2
    end
    add_message "ord_kit.Voltage" do
      proto3_optional :value, :double, 1
      proto3_optional :precision, :double, 2
      optional :units, :enum, 3, "ord_kit.Voltage.VoltageUnit"
    end
    add_enum "ord_kit.Voltage.VoltageUnit" do
      value :UNSPECIFIED, 0
      value :VOLT, 1
      value :MILLIVOLT, 2
    end
    add_message "ord_kit.Length" do
      proto3_optional :value, :double, 1
      proto3_optional :precision, :double, 2
      optional :units, :enum, 3, "ord_kit.Length.LengthUnit"
    end
    add_enum "ord_kit.Length.LengthUnit" do
      value :UNSPECIFIED, 0
      value :CENTIMETER, 1
      value :MILLIMETER, 2
      value :METER, 3
      value :INCH, 4
      value :FOOT, 5
    end
    add_message "ord_kit.Wavelength" do
      proto3_optional :value, :double, 1
      proto3_optional :precision, :double, 2
      optional :units, :enum, 3, "ord_kit.Wavelength.WavelengthUnit"
    end
    add_enum "ord_kit.Wavelength.WavelengthUnit" do
      value :UNSPECIFIED, 0
      value :NANOMETER, 1
      value :WAVENUMBER, 2
    end
    add_message "ord_kit.FlowRate" do
      proto3_optional :value, :double, 1
      proto3_optional :precision, :double, 2
      optional :units, :enum, 3, "ord_kit.FlowRate.FlowRateUnit"
    end
    add_enum "ord_kit.FlowRate.FlowRateUnit" do
      value :UNSPECIFIED, 0
      value :MICROLITER_PER_MINUTE, 1
      value :MICROLITER_PER_SECOND, 2
      value :MILLILITER_PER_MINUTE, 3
      value :MILLILITER_PER_SECOND, 4
      value :MICROLITER_PER_HOUR, 5
    end
    add_message "ord_kit.Percentage" do
      proto3_optional :value, :double, 1
      proto3_optional :precision, :double, 2
    end
    add_message "ord_kit.FloatValue" do
      proto3_optional :value, :double, 1
      proto3_optional :precision, :double, 2
    end
    add_message "ord_kit.Data" do
      optional :description, :string, 7
      optional :format, :string, 8
      oneof :kind do
        optional :double_value, :double, 1
        optional :float_value, :float, 2
        optional :integer_value, :int32, 3
        optional :bytes_value, :bytes, 4
        optional :string_value, :string, 5
        optional :url, :string, 6
      end
    end
    add_message "ord_kit.Automation" do
    end
    add_enum "ord_kit.Automation.AutomationType" do
      value :UNSPECIFIED, 0
      value :AUTOMATIC, 1
      value :MANUAL, 2
    end
  end
end

module OrdKit
  Reaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Reaction").msgclass
  ReactionStep = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionStep").msgclass
  ReactionIdentifier = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionIdentifier").msgclass
  ReactionIdentifier::IdentifierType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionIdentifier.IdentifierType").enummodule
  ReactionInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionInput").msgclass
  ReactionInput::AdditionSpeed = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionInput.AdditionSpeed").msgclass
  ReactionInput::AdditionSpeed::AdditionSpeedType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionInput.AdditionSpeed.AdditionSpeedType").enummodule
  ReactionAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionAction").msgclass
  ReactionActionAdd = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionActionAdd").msgclass
  ReactionActionRemove = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionActionRemove").msgclass
  ReactionActionEquip = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionActionEquip").msgclass
  ReactionActionEquip::EquipActionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionActionEquip.EquipActionType").enummodule
  ReactionActionCondition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionActionCondition").msgclass
  ReactionActionCondition::TendencyType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionActionCondition.TendencyType").enummodule
  ReactionActionMotion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionActionMotion").msgclass
  ReactionActionPurify = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionActionPurify").msgclass
  ReactionActionPurify::PurifyType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionActionPurify.PurifyType").enummodule
  ReactionActionPurify::FiltrationMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionActionPurify.FiltrationMode").enummodule
  ReactionActionTransfer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionActionTransfer").msgclass
  ReactionActionWait = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionActionWait").msgclass
  ReactionActionSaveSample = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionActionSaveSample").msgclass
  Amount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Amount").msgclass
  UnmeasuredAmount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.UnmeasuredAmount").msgclass
  UnmeasuredAmount::UnmeasuredAmountType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.UnmeasuredAmount.UnmeasuredAmountType").enummodule
  CrudeComponent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.CrudeComponent").msgclass
  Compound = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Compound").msgclass
  Compound::Source = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Compound.Source").msgclass
  ReactionRole = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionRole").msgclass
  ReactionRole::ReactionRoleType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionRole.ReactionRoleType").enummodule
  CompoundPreparation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.CompoundPreparation").msgclass
  CompoundPreparation::PreparationType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.CompoundPreparation.PreparationType").enummodule
  CompoundIdentifier = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.CompoundIdentifier").msgclass
  CompoundIdentifier::IdentifierType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.CompoundIdentifier.IdentifierType").enummodule
  Vessel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Vessel").msgclass
  Vessel::VesselType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Vessel.VesselType").enummodule
  VesselMaterial = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.VesselMaterial").msgclass
  VesselMaterial::VesselMaterialType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.VesselMaterial.VesselMaterialType").enummodule
  Equipment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Equipment").msgclass
  Equipment::EquipmentType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Equipment.EquipmentType").enummodule
  VesselAttachment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.VesselAttachment").msgclass
  VesselAttachment::VesselAttachmentType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.VesselAttachment.VesselAttachmentType").enummodule
  VesselPreparation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.VesselPreparation").msgclass
  VesselPreparation::VesselPreparationType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.VesselPreparation.VesselPreparationType").enummodule
  ReactionSetup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionSetup").msgclass
  ReactionSetup::ReactionEnvironment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionSetup.ReactionEnvironment").msgclass
  ReactionSetup::ReactionEnvironment::ReactionEnvironmentType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionSetup.ReactionEnvironment.ReactionEnvironmentType").enummodule
  ReactionConditions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionConditions").msgclass
  PhAdjustConditions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.PhAdjustConditions").msgclass
  PhAdjustConditions::PhAdjustMeasurementType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.PhAdjustConditions.PhAdjustMeasurementType").enummodule
  TemperatureConditions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.TemperatureConditions").msgclass
  TemperatureConditions::TemperatureControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.TemperatureConditions.TemperatureControl").msgclass
  TemperatureConditions::TemperatureControl::TemperatureControlType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.TemperatureConditions.TemperatureControl.TemperatureControlType").enummodule
  TemperatureConditions::Measurement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.TemperatureConditions.Measurement").msgclass
  TemperatureConditions::Measurement::MeasurementType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.TemperatureConditions.Measurement.MeasurementType").enummodule
  PressureConditions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.PressureConditions").msgclass
  PressureConditions::PressureControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.PressureConditions.PressureControl").msgclass
  PressureConditions::PressureControl::PressureControlType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.PressureConditions.PressureControl.PressureControlType").enummodule
  PressureConditions::Atmosphere = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.PressureConditions.Atmosphere").msgclass
  PressureConditions::Atmosphere::AtmosphereType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.PressureConditions.Atmosphere.AtmosphereType").enummodule
  PressureConditions::Measurement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.PressureConditions.Measurement").msgclass
  PressureConditions::Measurement::MeasurementType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.PressureConditions.Measurement.MeasurementType").enummodule
  StirringConditions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.StirringConditions").msgclass
  StirringConditions::StirringRate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.StirringConditions.StirringRate").msgclass
  StirringConditions::StirringRate::StirringRateType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.StirringConditions.StirringRate.StirringRateType").enummodule
  StirringConditions::StirringMethodType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.StirringConditions.StirringMethodType").enummodule
  IlluminationConditions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.IlluminationConditions").msgclass
  IlluminationConditions::IlluminationType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.IlluminationConditions.IlluminationType").enummodule
  ElectrochemistryConditions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ElectrochemistryConditions").msgclass
  ElectrochemistryConditions::Measurement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ElectrochemistryConditions.Measurement").msgclass
  ElectrochemistryConditions::ElectrochemistryCell = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ElectrochemistryConditions.ElectrochemistryCell").msgclass
  ElectrochemistryConditions::ElectrochemistryCell::ElectrochemistryCellType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ElectrochemistryConditions.ElectrochemistryCell.ElectrochemistryCellType").enummodule
  ElectrochemistryConditions::ElectrochemistryType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ElectrochemistryConditions.ElectrochemistryType").enummodule
  FlowConditions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.FlowConditions").msgclass
  FlowConditions::Tubing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.FlowConditions.Tubing").msgclass
  FlowConditions::Tubing::TubingType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.FlowConditions.Tubing.TubingType").enummodule
  FlowConditions::FlowType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.FlowConditions.FlowType").enummodule
  ReactionNotes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionNotes").msgclass
  ReactionObservation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionObservation").msgclass
  ReactionWorkup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionWorkup").msgclass
  ReactionWorkup::WorkupType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionWorkup.WorkupType").enummodule
  ReactionOutcome = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionOutcome").msgclass
  ProductCompound = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ProductCompound").msgclass
  ProductCompound::Texture = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ProductCompound.Texture").msgclass
  ProductCompound::Texture::TextureType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ProductCompound.Texture.TextureType").enummodule
  ProductMeasurement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ProductMeasurement").msgclass
  ProductMeasurement::MassSpecMeasurementDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ProductMeasurement.MassSpecMeasurementDetails").msgclass
  ProductMeasurement::MassSpecMeasurementDetails::MassSpecMeasurementType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ProductMeasurement.MassSpecMeasurementDetails.MassSpecMeasurementType").enummodule
  ProductMeasurement::Selectivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ProductMeasurement.Selectivity").msgclass
  ProductMeasurement::Selectivity::SelectivityType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ProductMeasurement.Selectivity.SelectivityType").enummodule
  ProductMeasurement::MeasurementType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ProductMeasurement.MeasurementType").enummodule
  DateTime = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.DateTime").msgclass
  Analysis = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Analysis").msgclass
  Analysis::AnalysisType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Analysis.AnalysisType").enummodule
  ReactionProvenance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.ReactionProvenance").msgclass
  Person = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Person").msgclass
  RecordEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.RecordEvent").msgclass
  Time = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Time").msgclass
  Time::TimeUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Time.TimeUnit").enummodule
  Mass = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Mass").msgclass
  Mass::MassUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Mass.MassUnit").enummodule
  Moles = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Moles").msgclass
  Moles::MolesUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Moles.MolesUnit").enummodule
  Volume = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Volume").msgclass
  Volume::VolumeUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Volume.VolumeUnit").enummodule
  Concentration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Concentration").msgclass
  Concentration::ConcentrationUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Concentration.ConcentrationUnit").enummodule
  Pressure = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Pressure").msgclass
  Pressure::PressureUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Pressure.PressureUnit").enummodule
  Temperature = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Temperature").msgclass
  Temperature::TemperatureUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Temperature.TemperatureUnit").enummodule
  Current = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Current").msgclass
  Current::CurrentUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Current.CurrentUnit").enummodule
  Voltage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Voltage").msgclass
  Voltage::VoltageUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Voltage.VoltageUnit").enummodule
  Length = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Length").msgclass
  Length::LengthUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Length.LengthUnit").enummodule
  Wavelength = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Wavelength").msgclass
  Wavelength::WavelengthUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Wavelength.WavelengthUnit").enummodule
  FlowRate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.FlowRate").msgclass
  FlowRate::FlowRateUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.FlowRate.FlowRateUnit").enummodule
  Percentage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Percentage").msgclass
  FloatValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.FloatValue").msgclass
  Data = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Data").msgclass
  Automation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Automation").msgclass
  Automation::AutomationType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ord_kit.Automation.AutomationType").enummodule
end
